name = "DCELs"
uuid = "8c28c835-e81c-4ea4-8d5c-7c9dbbfe5d06"
authors = ["Rodolfo Figueroa Soriano <4rodolfofigueroa2@gmail.com>"]
version = "0.1.0"

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
ResumableFunctions = "0.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
